CONFIG_GPIO=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_MCUX_TRNG=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

