// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalDash

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Dash_BG;
extern void ui_event_TopTach( lv_event_t * e);
extern lv_obj_t *ui_TopTach;
extern void ui_event_MainTach( lv_event_t * e);
extern lv_obj_t *ui_MainTach;
extern lv_obj_t *ui_MPH_Label;
extern lv_obj_t *ui_Coolant;
extern lv_obj_t *ui_Oil_Pressure;
extern lv_obj_t *ui_AFR;
extern lv_obj_t *ui_Oil_Temp;
extern lv_obj_t *ui_Ethanol;
extern lv_obj_t *ui_Battery;
extern lv_obj_t *ui_Gas_Level;
extern lv_obj_t *ui_Boost_Label;
extern lv_obj_t *ui_B_Meter;
extern lv_obj_t *ui_CEL_REG;
extern lv_obj_t *ui_OIL_REG;
extern lv_obj_t *ui_BAT_REG;
extern lv_obj_t *ui_TMP_REG;
extern lv_obj_t *ui_TCC_REG;
extern lv_obj_t *ui_CAN_REG;
extern lv_obj_t *ui_GPS_REG;
extern lv_obj_t *ui_Oil_Pressure_Overlay;
extern lv_obj_t *ui_Oil_Temp_Overlay;
extern lv_obj_t *ui_AFR_Overlay;
extern lv_obj_t *ui_Ethanol_Overlay;
extern lv_obj_t *ui_Battery_Overlay;
extern lv_obj_t *ui_Fuel_Overlay;
extern lv_obj_t *ui_Coolant_Overlay;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

