// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalDash

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Dash_BG = NULL;lv_obj_t *ui_TopTach = NULL;lv_obj_t *ui_MainTach = NULL;lv_obj_t *ui_MPH_Label = NULL;lv_obj_t *ui_Coolant = NULL;lv_obj_t *ui_Oil_Pressure = NULL;lv_obj_t *ui_AFR = NULL;lv_obj_t *ui_Oil_Temp = NULL;lv_obj_t *ui_Ethanol = NULL;lv_obj_t *ui_Battery = NULL;lv_obj_t *ui_Gas_Level = NULL;lv_obj_t *ui_Boost_Label = NULL;lv_obj_t *ui_B_Meter = NULL;lv_obj_t *ui_CEL_REG = NULL;lv_obj_t *ui_OIL_REG = NULL;lv_obj_t *ui_BAT_REG = NULL;lv_obj_t *ui_TMP_REG = NULL;lv_obj_t *ui_TCC_REG = NULL;lv_obj_t *ui_CAN_REG = NULL;lv_obj_t *ui_GPS_REG = NULL;lv_obj_t *ui_Oil_Pressure_Overlay = NULL;lv_obj_t *ui_Oil_Temp_Overlay = NULL;lv_obj_t *ui_AFR_Overlay = NULL;lv_obj_t *ui_Ethanol_Overlay = NULL;lv_obj_t *ui_Battery_Overlay = NULL;lv_obj_t *ui_Fuel_Overlay = NULL;lv_obj_t *ui_Coolant_Overlay = NULL;
// event funtions
void ui_event_TopTach( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      TopTachometer_Animation(ui_TopTach, 0);
}
}

void ui_event_MainTach( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      MainTachometer_Animation(ui_MainTach, 0);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dash_BG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Dash_BG, &ui_img_gauge_status_dash_bg2_png);
lv_obj_set_width( ui_Dash_BG, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_Dash_BG, LV_SIZE_CONTENT);   /// 272
lv_obj_set_align( ui_Dash_BG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dash_BG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Dash_BG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TopTach = lv_img_create(ui_Screen1);
lv_img_set_src(ui_TopTach, &ui_img_top_tach_toptach00001_png);
lv_obj_set_width( ui_TopTach, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TopTach, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TopTach, 0 );
lv_obj_set_y( ui_TopTach, -125 );
lv_obj_set_align( ui_TopTach, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TopTach, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TopTach, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MainTach = lv_img_create(ui_Screen1);
lv_img_set_src(ui_MainTach, &ui_img_main_tach_maintachometer00060_png);
lv_obj_set_width( ui_MainTach, LV_SIZE_CONTENT);  /// 461
lv_obj_set_height( ui_MainTach, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_MainTach, 0 );
lv_obj_set_y( ui_MainTach, -97 );
lv_obj_set_align( ui_MainTach, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MainTach, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MainTach, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MPH_Label = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_MPH_Label, 190);
lv_obj_set_height( ui_MPH_Label, 98);
lv_obj_set_x( ui_MPH_Label, -132 );
lv_obj_set_y( ui_MPH_Label, 20 );
lv_obj_set_align( ui_MPH_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_MPH_Label,"100");
lv_obj_set_style_text_color(ui_MPH_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MPH_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_MPH_Label, -3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_MPH_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MPH_Label, &ui_font_MPH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Coolant = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Coolant, 33);
lv_obj_set_height( ui_Coolant, 18);
lv_obj_set_x( ui_Coolant, -205 );
lv_obj_set_y( ui_Coolant, 118 );
lv_obj_set_align( ui_Coolant, LV_ALIGN_CENTER );
lv_label_set_text(ui_Coolant,"100");
lv_obj_set_style_text_color(ui_Coolant, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Coolant, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Coolant, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Coolant, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Coolant, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Oil_Pressure = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Oil_Pressure, 33);
lv_obj_set_height( ui_Oil_Pressure, 18);
lv_obj_set_x( ui_Oil_Pressure, -138 );
lv_obj_set_y( ui_Oil_Pressure, 118 );
lv_obj_set_align( ui_Oil_Pressure, LV_ALIGN_CENTER );
lv_label_set_text(ui_Oil_Pressure,"1.0");
lv_obj_set_style_text_color(ui_Oil_Pressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Oil_Pressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Oil_Pressure, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Oil_Pressure, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Oil_Pressure, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_AFR = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_AFR, 44);
lv_obj_set_height( ui_AFR, LV_SIZE_CONTENT);   /// 18
lv_obj_set_x( ui_AFR, 0 );
lv_obj_set_y( ui_AFR, 118 );
lv_obj_set_align( ui_AFR, LV_ALIGN_CENTER );
lv_label_set_text(ui_AFR,"12.1");
lv_obj_set_style_text_color(ui_AFR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AFR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AFR, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_AFR, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_AFR, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Oil_Temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Oil_Temp, 33);
lv_obj_set_height( ui_Oil_Temp, 18);
lv_obj_set_x( ui_Oil_Temp, -73 );
lv_obj_set_y( ui_Oil_Temp, 118 );
lv_obj_set_align( ui_Oil_Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Oil_Temp,"100");
lv_obj_set_style_text_color(ui_Oil_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Oil_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Oil_Temp, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Oil_Temp, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Oil_Temp, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Ethanol = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Ethanol, 33);
lv_obj_set_height( ui_Ethanol, 18);
lv_obj_set_x( ui_Ethanol, 65 );
lv_obj_set_y( ui_Ethanol, 118 );
lv_obj_set_align( ui_Ethanol, LV_ALIGN_CENTER );
lv_label_set_text(ui_Ethanol,"E85");
lv_obj_set_style_text_color(ui_Ethanol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Ethanol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Ethanol, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Ethanol, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Ethanol, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Battery = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Battery, 44);
lv_obj_set_height( ui_Battery, 18);
lv_obj_set_x( ui_Battery, 128 );
lv_obj_set_y( ui_Battery, 118 );
lv_obj_set_align( ui_Battery, LV_ALIGN_CENTER );
lv_label_set_text(ui_Battery,"12.1");
lv_obj_set_style_text_color(ui_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Battery, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Battery, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Battery, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Gas_Level = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Gas_Level, 33);
lv_obj_set_height( ui_Gas_Level, 18);
lv_obj_set_x( ui_Gas_Level, 190 );
lv_obj_set_y( ui_Gas_Level, 118 );
lv_obj_set_align( ui_Gas_Level, LV_ALIGN_CENTER );
lv_label_set_text(ui_Gas_Level,"99");
lv_obj_set_style_text_color(ui_Gas_Level, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Gas_Level, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Gas_Level, &ui_font_Gauges, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Gas_Level, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Gas_Level, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Boost_Label = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Boost_Label, 163);
lv_obj_set_height( ui_Boost_Label, 43);
lv_obj_set_x( ui_Boost_Label, 147 );
lv_obj_set_y( ui_Boost_Label, 0 );
lv_obj_set_align( ui_Boost_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Boost_Label,"-8.5");
lv_obj_set_style_text_color(ui_Boost_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Boost_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Boost_Label, &ui_font_BOOST, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Boost_Label, lv_color_hex(0xFFB300), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Boost_Label, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_color(ui_Boost_Label, lv_color_hex(0xFF1A1A), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_text_opa(ui_Boost_Label, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_B_Meter = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_B_Meter, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_B_Meter)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_B_Meter, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_B_Meter, 161);
lv_obj_set_height( ui_B_Meter, 6);
lv_obj_set_x( ui_B_Meter, 149 );
lv_obj_set_y( ui_B_Meter, 45 );
lv_obj_set_align( ui_B_Meter, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_B_Meter, LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_set_style_radius(ui_B_Meter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_B_Meter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_B_Meter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_B_Meter, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_B_Meter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_B_Meter, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_B_Meter, &ui_img_boostmeter_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_B_Meter, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_B_Meter, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_B_Meter, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_B_Meter, true, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_B_Meter, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_CEL_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_CEL_REG, &ui_img_661487214);
lv_obj_set_width( ui_CEL_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_CEL_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_CEL_REG, -220 );
lv_obj_set_y( ui_CEL_REG, -55 );
lv_obj_set_align( ui_CEL_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CEL_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CEL_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_grad_color(ui_CEL_REG, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_img_recolor(ui_CEL_REG, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_CEL_REG, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_CEL_REG, lv_color_hex(0x00E0FF), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_CEL_REG, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor(ui_CEL_REG, lv_color_hex(0xFF2A2A), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_img_recolor_opa(ui_CEL_REG, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_OIL_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_OIL_REG, &ui_img_420241965);
lv_obj_set_width( ui_OIL_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_OIL_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_OIL_REG, -198 );
lv_obj_set_y( ui_OIL_REG, -55 );
lv_obj_set_align( ui_OIL_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OIL_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OIL_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_OIL_REG, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_OIL_REG, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_OIL_REG, lv_color_hex(0x00E0FF), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_OIL_REG, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor(ui_OIL_REG, lv_color_hex(0xFF2A2A), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_img_recolor_opa(ui_OIL_REG, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_BAT_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_BAT_REG, &ui_img_1501971144);
lv_obj_set_width( ui_BAT_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_BAT_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_BAT_REG, -175 );
lv_obj_set_y( ui_BAT_REG, -55 );
lv_obj_set_align( ui_BAT_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BAT_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BAT_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TMP_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_TMP_REG, &ui_img_1711266973);
lv_obj_set_width( ui_TMP_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_TMP_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_TMP_REG, -152 );
lv_obj_set_y( ui_TMP_REG, -55 );
lv_obj_set_align( ui_TMP_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TMP_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TMP_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TCC_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_TCC_REG, &ui_img_1148324094);
lv_obj_set_width( ui_TCC_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_TCC_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_TCC_REG, -129 );
lv_obj_set_y( ui_TCC_REG, -55 );
lv_obj_set_align( ui_TCC_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TCC_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TCC_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CAN_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_CAN_REG, &ui_img_2064914023);
lv_obj_set_width( ui_CAN_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_CAN_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_CAN_REG, -106 );
lv_obj_set_y( ui_CAN_REG, -55 );
lv_obj_set_align( ui_CAN_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CAN_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CAN_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_GPS_REG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_GPS_REG, &ui_img_983184844);
lv_obj_set_width( ui_GPS_REG, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_GPS_REG, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_GPS_REG, -83 );
lv_obj_set_y( ui_GPS_REG, -55 );
lv_obj_set_align( ui_GPS_REG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GPS_REG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_GPS_REG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Oil_Pressure_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Oil_Pressure_Overlay, &ui_img_gauge_status_gauge_tile00000_png);
lv_obj_set_width( ui_Oil_Pressure_Overlay, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Oil_Pressure_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_Oil_Pressure_Overlay, -132 );
lv_obj_set_y( ui_Oil_Pressure_Overlay, 109 );
lv_obj_set_align( ui_Oil_Pressure_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Oil_Pressure_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Oil_Pressure_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Oil_Pressure_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Oil_Pressure_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Oil_Pressure_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_Oil_Pressure_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Oil_Temp_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Oil_Temp_Overlay, &ui_img_gauge_status_gauge_tile00001_png);
lv_obj_set_width( ui_Oil_Temp_Overlay, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Oil_Temp_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_Oil_Temp_Overlay, -66 );
lv_obj_set_y( ui_Oil_Temp_Overlay, 109 );
lv_obj_set_align( ui_Oil_Temp_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Oil_Temp_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Oil_Temp_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Oil_Temp_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Oil_Temp_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Oil_Temp_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_Oil_Temp_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_AFR_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_AFR_Overlay, &ui_img_gauge_status_gauge_tile00002_png);
lv_obj_set_width( ui_AFR_Overlay, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_AFR_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_AFR_Overlay, 0 );
lv_obj_set_y( ui_AFR_Overlay, 109 );
lv_obj_set_align( ui_AFR_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AFR_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_AFR_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AFR_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AFR_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_AFR_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_AFR_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Ethanol_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Ethanol_Overlay, &ui_img_gauge_status_gauge_tile00003_png);
lv_obj_set_width( ui_Ethanol_Overlay, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Ethanol_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_Ethanol_Overlay, 66 );
lv_obj_set_y( ui_Ethanol_Overlay, 109 );
lv_obj_set_align( ui_Ethanol_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Ethanol_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Ethanol_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Ethanol_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Ethanol_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Ethanol_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_Ethanol_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Battery_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Battery_Overlay, &ui_img_gauge_status_gauge_tile00004_png);
lv_obj_set_width( ui_Battery_Overlay, LV_SIZE_CONTENT);  /// 65
lv_obj_set_height( ui_Battery_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_Battery_Overlay, 133 );
lv_obj_set_y( ui_Battery_Overlay, 109 );
lv_obj_set_align( ui_Battery_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Battery_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Battery_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Battery_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Battery_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_Battery_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Fuel_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Fuel_Overlay, &ui_img_gauge_status_gauge_tile00005_png);
lv_obj_set_width( ui_Fuel_Overlay, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Fuel_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_Fuel_Overlay, 199 );
lv_obj_set_y( ui_Fuel_Overlay, 109 );
lv_obj_set_align( ui_Fuel_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Fuel_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Fuel_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Fuel_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Fuel_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Fuel_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_Fuel_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_Coolant_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Coolant_Overlay, &ui_img_gauge_status_gauge_tile00006_png);
lv_obj_set_width( ui_Coolant_Overlay, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Coolant_Overlay, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_Coolant_Overlay, -198 );
lv_obj_set_y( ui_Coolant_Overlay, 109 );
lv_obj_set_align( ui_Coolant_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Coolant_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Coolant_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Coolant_Overlay, lv_color_hex(0x0A0F17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Coolant_Overlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Coolant_Overlay, lv_color_hex(0xFF1A1A), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_img_recolor_opa(ui_Coolant_Overlay, 255, LV_PART_MAIN| LV_STATE_USER_1);

lv_obj_add_event_cb(ui_TopTach, ui_event_TopTach, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MainTach, ui_event_MainTach, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Dash_BG= NULL;
ui_TopTach= NULL;
ui_MainTach= NULL;
ui_MPH_Label= NULL;
ui_Coolant= NULL;
ui_Oil_Pressure= NULL;
ui_AFR= NULL;
ui_Oil_Temp= NULL;
ui_Ethanol= NULL;
ui_Battery= NULL;
ui_Gas_Level= NULL;
ui_Boost_Label= NULL;
ui_B_Meter= NULL;
ui_CEL_REG= NULL;
ui_OIL_REG= NULL;
ui_BAT_REG= NULL;
ui_TMP_REG= NULL;
ui_TCC_REG= NULL;
ui_CAN_REG= NULL;
ui_GPS_REG= NULL;
ui_Oil_Pressure_Overlay= NULL;
ui_Oil_Temp_Overlay= NULL;
ui_AFR_Overlay= NULL;
ui_Ethanol_Overlay= NULL;
ui_Battery_Overlay= NULL;
ui_Fuel_Overlay= NULL;
ui_Coolant_Overlay= NULL;

}
